on: [push, pull_request]

name: Main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update rustup
        run: rustup update
      - name: Compile
        run: cargo build --release
      - name: Install cargo-deb
        run: cargo install cargo-deb
      - name: Package .deb
        run: cargo deb
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update rustup
        run: rustup update
      - name: Clippy
        run: cargo clippy -- -Dwarnings
